@startuml
skinparam classAttributeIconSize 0

class CsvImporter {
    + {static} importContacts(Model, String): void
}

CsvImporter ..> IOException : throws >
CsvImporter ..> DeserialisePersonException : throws >
@enduml
